### ISSUE TITLE
UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel-2017-12-05.log" could not be opened: faile...

### ISSUE THREAD

**Issue by HaroenViaene** [votepen/platform#10]
https://sentry.io/votepen/votepen/issues/413132924/

    UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel-2017-12-05.log" could not be opened: failed to open stream: Permission denied
      File "app/Exceptions/Handler.php", line 44, in report
        parent::report($exception);
    ...
    (7 additional frame(s) were not displayed)

**Comment by yoginth** [comment]
**Thanks**, The issue has been fixed already!
